### ISSUE TITLE
What's the difference between kinesis firehose and Kinesis stream?

### ISSUE THREAD

**Issue by rbngtm1** [ravsau/aws-exam-prep#10]

**Comment by ravsau** [comment]
The main difference:
- Kinesis Streams just store the data in the stream. You should setup consumers to do something with it. So a lambda function and an EC2 instance can be reading from that stream at the same time and generating something or transforming data. Then an action can be taken, like send someone a message or store data in S3.
- Kinesis Firehose is meant to be used when you want to collect streaming data and store it in one of the 4 destinations. S3, Redshift, Splunk , Elasticsearch. 

To sumarize, firehose is send data to somewhere. Kinesis data streams on the other hand store data for upto 7 days for you to work with process.

![image](https://user-images.githubusercontent.com/22568316/43876219-0d4d6d32-9b62-11e8-93a3-22c54a9eaf01.png)
