### ISSUE TITLE
Scenario Questions about instances and AZ's

### ISSUE THREAD

**Issue by rbngtm1** [ravsau/aws-exam-prep#13]
1. An application is in us-west-2, --requires 6 instances running all time,
    (Using 3AZ in a region, which provides 100% fault tolerance if any single AZ is unavailable?)
Ans: a)us-west-2a=6 instance; us-wet-2b=6instance; 2c=0 instance **(PLEASE EXPLAIN WHY?**)OR
        b}us-west-2a=3 instance; 2b=3 instance; 2c=3 instance **(PLEASE EXPLAIN WHY?)**
2. If you have 4 instances (best option for fault tolerance and high availability)
Ans: Deploy 2 instance in each of 3AZ, add ELB and Autoscaling group to Launch more instance. **(PLEASE EXPLAIN -Why should I deploy 2 instances in 3AZ?)**

**Comment by ravsau** [comment]
## Ans for 1
You need to have 6 instances at all times.  The answer choice a will have 6 servers remaining even if 1 AZ goes down. Same with choice B

## Ans for 2 
Similar idea, if one AZ goes down, you still have 4 EC2 remaining in the other 2 AZ's.
