### ISSUE TITLE
Creating A Stack From CLI

### ISSUE THREAD

**Issue by LA25REDZ** [ravsau/aws-exam-prep#15]
Good Morning Saurav, 

Question: How can we create a stack in from the CLI for cloudformation if we typing everything from scratch without knowing the parameters?  We did everything from scratch in class from the AWS console where we could choose the ImageID, instancetype, subnetID, vpcID, etc. If we are using the CLI option how do we know what to attached and link to what in the script?

**Comment by ravsau** [comment]
Great question!
your command will look like this if you have 2 parameters:
```
aws cloudformation create stack --template-body file://template.yaml --parameters  ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro
```
---
Alternatively , you can create a parameters file like this:
```
[
  {
    "ParameterKey": "KeyPairName",
    "ParameterValue": "MyKey"
  }, 
  {
    "ParameterKey": "InstanceType",
    "ParameterValue": "m1.micro"
  }
]
``` 

and you can pass the name of the parameter file in the CLI command like this,
```
aws cloudformation create stack --template-body file://template.yaml --parameters file://params.json
```

**Comment by LA25REDZ** [comment]
Thx

**Comment by LA25REDZ** [comment]
I passed my AWS Developer Exam

**Comment by ravsau** [comment]
Congratulations Lawrence! That's great news!
